apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ngo-service
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - solidarytech
  selector:
    matchLabels:
      app: ngo-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: donation-service
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - solidarytech
  selector:
    matchLabels:
      app: donation-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: volunteer-service
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - solidarytech
  selector:
    matchLabels:
      app: volunteer-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
