apiVersion: v1
kind: ServiceAccount
metadata:
  name: volunteer-service-sa
  namespace: solidarytech
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::215671569122:role/solidarytech-volunteer-service-role
