apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: solidarytech

commonLabels:
  cost-center: ngo-core
  environment: production
  project: solidarytech

# Imagens substituídas pela CI/CD via:
# kustomize edit set image ... no workflow
# O ACCOUNT_ID real é injetado via GitHub Secret AWS_ACCOUNT_ID
images:
- name: solidarytech/donation-service
  newName: 215671569122.dkr.ecr.us-east-1.amazonaws.com/solidarytech/donation-service
  newTag: de2c5c4a0ad21a44a4f1f36575b6d70818155de2
- name: solidarytech/ngo-service
  newName: 215671569122.dkr.ecr.us-east-1.amazonaws.com/solidarytech/ngo-service
  newTag: 291ab92f2abf6ad9f5b20c715c066977efb447ba
- name: solidarytech/volunteer-service
  newName: 215671569122.dkr.ecr.us-east-1.amazonaws.com/solidarytech/volunteer-service
  newTag: 291ab92f2abf6ad9f5b20c715c066977efb447ba
resources:
- ../../base
