apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: solidarytech

commonLabels:
  cost-center: ngo-core
  environment: production
  project: solidarytech

# Imagens substituídas pela CI/CD via:
# kustomize edit set image ... no workflow
# O ACCOUNT_ID real é injetado via GitHub Secret AWS_ACCOUNT_ID
images:
- name: solidarytech/donation-service
  newName: 215671569122.dkr.ecr.us-east-1.amazonaws.com/solidarytech/donation-service
  newTag: 5504d9411bd898f75acfea2af0df8575b5d8cc52
- name: solidarytech/ngo-service
  newName: 215671569122.dkr.ecr.us-east-1.amazonaws.com/solidarytech/ngo-service
  newTag: 93f472ed95d2adb652b8bc459525d28c8d90c45c
- name: solidarytech/volunteer-service
  newName: 215671569122.dkr.ecr.us-east-1.amazonaws.com/solidarytech/volunteer-service
  newTag: 93f472ed95d2adb652b8bc459525d28c8d90c45c
resources:
- ../../base
