apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: solidarytech

commonLabels:
  cost-center: ngo-core
  environment: production
  project: solidarytech

# Imagens substituídas pela CI/CD via:
# kustomize edit set image ... no workflow
# O ACCOUNT_ID real é injetado via GitHub Secret AWS_ACCOUNT_ID
images:
- name: solidarytech/donation-service
  newName: 215671569122.dkr.ecr.us-east-1.amazonaws.com/solidarytech/donation-service
  newTag: f0de5a8282d0fe7a2d76fbc2d9ea1e83250e246e
- name: solidarytech/ngo-service
  newName: 215671569122.dkr.ecr.us-east-1.amazonaws.com/solidarytech/ngo-service
  newTag: f0de5a8282d0fe7a2d76fbc2d9ea1e83250e246e
- name: solidarytech/volunteer-service
  newName: 215671569122.dkr.ecr.us-east-1.amazonaws.com/solidarytech/volunteer-service
  newTag: f0de5a8282d0fe7a2d76fbc2d9ea1e83250e246e
resources:
- ../../base
