apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace/namespace.yaml
  - monitoring/service-monitors.yaml
  - monitoring/prometheus-rules.yaml
  - monitoring/grafana-dashboard-sre.yaml
  - ngo-service/db-init-job.yaml
  - ngo-service/deployment.yaml
  - ngo-service/service.yaml
  - ngo-service/hpa.yaml
  - donation-service/db-init-job.yaml
  - donation-service/deployment.yaml
  - donation-service/service.yaml
  - donation-service/hpa.yaml
  - volunteer-service/deployment.yaml
  - volunteer-service/service.yaml
  - volunteer-service/hpa.yaml
  - volunteer-service/serviceaccount.yaml
