name: Deploy All Services

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  ngo-service:
    uses: ./.github/workflows/ngo-service.yml
    secrets: inherit

  donation-service:
    uses: ./.github/workflows/donation-service.yml
    secrets: inherit

  volunteer-service:
    uses: ./.github/workflows/volunteer-service.yml
    secrets: inherit
